### ISSUE TITLE
Is the method to login harcoded?

### ISSUE THREAD

**Issue by abishekbalu** [rahulkumarravindran/stock-trader#1]
I don't understand if this line is hardcoded to log in to the application! The below link refers to the line which I didn't understand. 

https://github.com/rahulkumarravindran/stock-trader/blob/a8147d78cdcfaef5159c6830be59943b32849092/src/App.js#L8

By the Way, I am learning ReactJS and trying to code the Welcome Page

**Comment by rahulkumarravindran** [comment]
added the state just for testing out the login page
You can remove the data inside it. It will still work. That state stores values from the sign up form and uses that data to authenticate the login.

**Comment by abishekbalu** [comment]
Understood the Issue!!,
